# Generated by Django 3.2.6 on 2021-08-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Famous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('info', models.TextField(max_length=100)),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='Pizza/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
